@startuml
left to right direction
skinparam roundcorner 5
skinparam linetype ortho
skinparam shadowing false
skinparam handwritten false
skinparam class {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

table( eko_eintrag_medikament ) {
  primary_key( id ): INTEGER
  column( pharma_nummer ) : CHARACTER VARYING(7)
  column( register_nummer_prefix ) : CHARACTER VARYING(2)
  column( register_nummer ) : CHARACTER VARYING(6)
  column( name ) : CHARACTER VARYING(100)
  column( darreichungsform ) : CHARACTER VARYING(9)
  column( teilbarkeit ) : CHARACTER VARYING(3)
  column( packungshinweis ) : CHARACTER VARYING(28)
  column( wirkstoff_information ) : CHARACTER VARYING(2048)
  column( box ) : CHARACTER(1)
  column( kassenzeichen ) : CHARACTER VARYING(3)
  column( kassenverkaufspreis ) : NUMBER
  column( kvp_pro_einheit ) : NUMBER
  column( preismodell ) : CHARACTER VARYING(3)
  column( regeltext ) : CHARACTER VARYING(2048)
  column( hinweis ) : CHARACTER VARYING(2048)
  column( langzeitbewilligung ) : CHARACTER VARYING(3)
  column( suchtgiftvignete ) : CHARACTER VARYING(3)
  column( rezeptflicht ) : INTEGER
  column( rezeptpflicht_bezeichnung) : CHARACTER VARYING(60)
  column( abgabeanzahl ) : INTEGER
  column( position_preisvergleich) : INTEGER
  column( indikations_text) : CHARACTER VARYING(2000)
  column( valid_date ): DATE
}

table( chemische_substanz ){
 primary_key(id): INTEGER
 column(code): CHARACTER VARYING(7)
 column(text): CHARACTER VARYING(128)
 column( valid_date ): DATE
}
table( chemische_untergruppe ){
 primary_key(id): INTEGER
 column(code): CHARACTER VARYING(5)
 column(text): CHARACTER VARYING(128)
 column( valid_date ): DATE
}
table( pharmakologische_untergruppe ){
 primary_key(id): INTEGER
 column(code): CHARACTER VARYING(4)
 column(text): CHARACTER VARYING(128)
 column( valid_date ): DATE
}
table(therapeutische_untergruppe){
 primary_key(id): INTEGER
 column(code): CHARACTER VARYING(3)
 column(text): CHARACTER VARYING(128)
 column( valid_date ): DATE
}
table(anatomische_hauptgruppe){
 primary_key(id): INTEGER
 column(code): CHARACTER VARYING(1)
 column(text): CHARACTER VARYING(128)
 column( valid_date ): DATE
}

table( wirkstoff ){
	primary_key( id ): INTEGER
	column( laufnummer ): INTEGER
	column( wirkstoff_staerke ): CHARACTER VARYING(10)
	column( dimension_wirkstoff_staerke ): CHARACTER VARYING(9)
	column( wirkstoff_eigenschaft ) : CHARACTER VARYING(20)
	foreign_key( wirk_atc_code) : INTEGER <<FK>>
	foreign_key( phar_atc_code ): INTEGER <<FK>>
	foreign_key( eko_eintrag_medikament_id ) : INTEGER <<FK>>
}

table(medikament_vergleich){
	primary_key( id ) : INTEGER
	column( vergleichs_kennzeichen ) : INTEGER
    foreign_key(medikament): INTEGER <<FK>>
	foreign_key( vergleichs_medikament ) : INTEGER <<FK>>
}

eko_eintrag_medikament "1" -- "1..*" wirkstoff
eko_eintrag_medikament "*" -- "*" eko_eintrag_medikament
( eko_eintrag_medikament, eko_eintrag_medikament) .. medikament_vergleich
chemische_substanz "*" -- "1" chemische_untergruppe
chemische_untergruppe "*" -- "1" pharmakologische_untergruppe
pharmakologische_untergruppe "*" -- "1" therapeutische_untergruppe
therapeutische_untergruppe "*" -- "1" anatomische_hauptgruppe
wirkstoff "*" -- "0..1" chemische_untergruppe
wirkstoff "*" -- "0..1" chemische_substanz

@enduml